# Generated by Django 4.2.2 on 2023-07-19 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_attendance_unique_together_patientsignout'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
