# Generated by Django 4.2.2 on 2023-07-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='adminkezz@gmail.com', max_length=100),
        ),
    ]
