# Generated by Django 4.2.2 on 2023-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='adminkezz@gmail.com', max_length=100, unique=True),
        ),
    ]
