# Generated by Django 4.2.2 on 2023-07-22 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0015_alter_patientsignout_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsignout',
            name='incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
