# Generated by Django 4.2.2 on 2023-07-23 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_attendance_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
