# Generated by Django 4.2.2 on 2023-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_patient_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
