# Generated by Django 4.2.2 on 2023-07-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_patient_room_number_alter_patient_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='room_number',
        ),
        migrations.AddField(
            model_name='attendance',
            name='patient_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], default='outpatient', max_length=20),
        ),
    ]
