# Generated by Django 4.2.2 on 2023-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_patient_patient_type_alter_patient_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], max_length=20),
        ),
    ]
