# Generated by Django 4.2.2 on 2023-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_alter_patient_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='patient_type',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], max_length=20),
        ),
    ]
