# Generated by Django 4.2.2 on 2023-07-23 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_alter_attendance_patient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='signed_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='room_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
