# Generated by Django 4.2.2 on 2023-07-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_patientsignout_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsignout',
            name='is_inpatient',
        ),
    ]
