# Generated by Django 4.2.2 on 2023-07-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_remove_patientsignout_is_inpatient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientsignout',
            unique_together={('check_in', 'patient')},
        ),
        migrations.RemoveField(
            model_name='patientsignout',
            name='incharge',
        ),
    ]
