# Generated by Django 4.2.2 on 2023-07-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_alter_patientsignout_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsignout',
            name='activities',
        ),
    ]
